apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdep-deployment
  namespace: jkpgcity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdep
  template:
    metadata:
      labels:
        app: webdep
    spec:
      containers:
      - name: webdep
        env:
        - name: DB_HOST
          value: "172.17.0.1"
        image: 193.10.212.89:5000/webdep